import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, Sparkles, Send, Trash2, Calendar, User, Folder, Award, Clock } from 'lucide-react';
import toast from 'react-hot-toast';
import { callClaude } from '../../lib/anthropic';
import Avatar from '../ui/Avatar';
import StatusBadge from '../ui/StatusBadge';
import PriorityBadge from '../ui/PriorityBadge';
import { TEAM_MEMBERS, PROJECTS } from '../../data/tasks';
import { useClickOutside } from '../../hooks/useClickOutside';

export default function TaskDetailSheet({ task, isOpen, onClose, onUpdate, onDelete, isMobile }) {
  if (!task) return null;

  const [title, setTitle] = useState(task.title);
  const [status, setStatus] = useState(task.status);
  const [priority, setPriority] = useState(task.priority);
  const [project, setProject] = useState(task.project);
  const [assignee, setAssignee] = useState(task.assignee);
  const [dueDate, setDueDate] = useState(task.dueDate);
  const [sprint, setSprint] = useState(task.sprint || 'Sprint 4');
  const [description, setDescription] = useState(task.description || '');
  const [aiWriting, setAiWriting] = useState(false);
  const [aiAnalyzing, setAiAnalyzing] = useState(false);
  const [aiAnalysis, setAiAnalysis] = useState('');

  // Dropdown states inside sheet
  const [activeDropdown, setActiveDropdown] = useState(null); // 'status' | 'priority' | 'assignee' | 'project'
  const sheetRef = useRef(null);

  // Sync state when task changes
  useEffect(() => {
    setTitle(task.title);
    setStatus(task.status);
    setPriority(task.priority);
    setProject(task.project);
    setAssignee(task.assignee);
    setDueDate(task.dueDate);
    setSprint(task.sprint || 'Sprint 4');
    setDescription(task.description || '');
    setAiAnalysis('');
  }, [task]);

  const handleSave = () => {
    onUpdate(task.id, {
      title,
      status,
      priority,
      project,
      assignee,
      dueDate,
      sprint,
      description
    });
    toast.success(`Task ${task.id} updated`, {
      style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderRadius: '12px' }
    });
    onClose();
  };

  const handleDelete = () => {
    onDelete(task.id);
    toast.error(`Task ${task.id} deleted`, {
      style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderRadius: '12px' }
    });
    onClose();
  };

  const handleAiWrite = async () => {
    setAiWriting(true);
    try {
      const prompt = `Write a professional, concise task description (2-3 sentences) for a technical task with this title: "${title}". Make it practical, including goals and definition of done. Do not output anything other than the description.`;
      const response = await callClaude(
        'You are an expert technical product owner and software architect.',
        prompt,
        [],
        300
      );
      setDescription(response.trim());
      toast.success('✦ Description generated by AI', {
        style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderLeft: '3px solid #06b6d4', borderRadius: '12px' }
      });
    } catch (err) {
      toast.error('AI Write failed. Please check your API key.', {
        style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderRadius: '12px' }
      });
    } finally {
      setAiWriting(false);
    }
  };

  const handleAiAnalysis = async () => {
    setAiAnalyzing(true);
    setAiAnalysis('');
    try {
      const prompt = `Analyze this task and provide:
1) RISK ASSESSMENT (1-2 sentences): potential bottlenecks or dependencies.
2) SUGGESTED NEXT STEPS (3 bullet points).
3) ESTIMATED COMPLETION TIME (e.g. 6 hours, 2 days).
Task: "${title}"
Status: "${status}"
Priority: "${priority}"
Assignee: "${assignee.name}"
Project: "${project}"
Description: "${description}"

Output the analysis in clean, structured markdown. Be concise and highly technical.`;

      const response = await callClaude(
        'You are a high-fidelity development risk analyst. Provide highly targeted technical feedback.',
        prompt,
        [],
        500
      );

      // Simulate streaming/token rendering for premium UX effect
      let currentText = '';
      const tokens = response.split(' ');
      for (let i = 0; i < tokens.length; i++) {
        await new Promise(r => setTimeout(r, 20));
        currentText += (i === 0 ? '' : ' ') + tokens[i];
        setAiAnalysis(currentText);
      }

      toast.success('✦ Task analysis complete', {
        style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderLeft: '3px solid #06b6d4', borderRadius: '12px' }
      });
    } catch (err) {
      toast.error('AI Analysis failed. Check your API key.', {
        style: { background: '#18181b', color: '#fafafa', border: '1px solid #3f3f46', borderRadius: '12px' }
      });
    } finally {
      setAiAnalyzing(false);
    }
  };

  // Sheet variants
  const desktopVariants = {
    closed: { x: '100%', opacity: 0.9 },
    open: { x: 0, opacity: 1 }
  };

  const mobileVariants = {
    closed: { y: '100%' },
    open: { y: 0 }
  };

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          {/* Backdrop blur overlay */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 bg-black/60 backdrop-blur-sm z-50 transition-opacity"
          />

          {/* Slide-over panel */}
          <motion.div
            ref={sheetRef}
            initial={isMobile ? 'closed' : 'closed'}
            animate="open"
            exit="closed"
            variants={isMobile ? mobileVariants : desktopVariants}
            transition={{ type: 'spring', stiffness: 300, damping: 30 }}
            className={`fixed bg-zinc-950 border-zinc-800 z-50 flex flex-col shadow-2xl overflow-hidden ${
              isMobile 
                ? 'bottom-0 left-0 right-0 h-[85vh] rounded-t-2xl border-t' 
                : 'top-0 right-0 w-[480px] h-full border-l'
            }`}
          >
            {/* Header */}
            <div className="px-6 py-4 border-b border-zinc-800 flex items-center justify-between shrink-0">
              <span className="font-mono text-xs text-zinc-500 font-semibold tracking-wider">
                {task.id}
              </span>
              <button
                type="button"
                onClick={onClose}
                aria-label="Close detail sheet"
                className="w-8 h-8 rounded-lg hover:bg-zinc-900 flex items-center justify-center text-zinc-500 hover:text-zinc-300 transition-colors cursor-pointer"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Scrollable Body */}
            <div className="flex-1 overflow-y-auto px-6 py-5 space-y-6">
              
              {/* Editable Title */}
              <div>
                <textarea
                  value={title}
                  onChange={e => setTitle(e.target.value)}
                  placeholder="Task title"
                  rows={2}
                  className="w-full bg-transparent border-none outline-none resize-none text-xl font-semibold text-zinc-50 focus:ring-0 placeholder:text-zinc-700 font-sans p-0 m-0"
                />
              </div>

              {/* Properties Grid */}
              <div className="grid grid-cols-2 gap-y-4 gap-x-6 border-b border-zinc-800/60 pb-6">
                
                {/* Status */}
                <div className="relative">
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Status
                  </span>
                  <button
                    type="button"
                    onClick={() => setActiveDropdown(activeDropdown === 'status' ? null : 'status')}
                    className="flex items-center gap-1 hover:opacity-85 active:scale-95 duration-100 transition-transform"
                  >
                    <StatusBadge status={status} />
                  </button>
                  {activeDropdown === 'status' && (
                    <div className="absolute top-full left-0 mt-1.5 w-44 bg-zinc-900 border border-zinc-800 rounded-xl shadow-xl z-50 py-1">
                      {['todo', 'in_progress', 'in_review', 'done', 'blocked'].map(s => (
                        <button
                          key={s}
                          type="button"
                          onClick={() => { setStatus(s); setActiveDropdown(null); }}
                          className={`w-full px-3 py-2 text-xs text-left hover:bg-zinc-800 transition-colors flex items-center gap-2 ${
                            status === s ? 'text-violet-400 font-semibold' : 'text-zinc-300'
                          }`}
                        >
                          <span className={`w-1.5 h-1.5 rounded-full ${s === 'todo' ? 'bg-zinc-500' : s === 'in_progress' ? 'bg-blue-500' : s === 'in_review' ? 'bg-amber-500' : s === 'done' ? 'bg-emerald-500' : 'bg-red-500'}`} />
                          {s === 'todo' ? 'Todo' : s === 'in_progress' ? 'In Progress' : s === 'in_review' ? 'In Review' : s === 'done' ? 'Done' : 'Blocked'}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* Priority */}
                <div className="relative">
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Priority
                  </span>
                  <button
                    type="button"
                    onClick={() => setActiveDropdown(activeDropdown === 'priority' ? null : 'priority')}
                    className="flex items-center gap-1 hover:opacity-85 active:scale-95 duration-100 transition-transform"
                  >
                    <PriorityBadge priority={priority} />
                  </button>
                  {activeDropdown === 'priority' && (
                    <div className="absolute top-full left-0 mt-1.5 w-44 bg-zinc-900 border border-zinc-800 rounded-xl shadow-xl z-50 py-1">
                      {['urgent', 'high', 'medium', 'low', 'none'].map(p => (
                        <button
                          key={p}
                          type="button"
                          onClick={() => { setPriority(p); setActiveDropdown(null); }}
                          className={`w-full px-3 py-2 text-xs text-left hover:bg-zinc-800 transition-colors ${
                            priority === p ? 'text-violet-400 font-semibold' : 'text-zinc-300'
                          }`}
                        >
                          {p.toUpperCase()}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* Assignee */}
                <div className="relative">
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Assignee
                  </span>
                  <button
                    type="button"
                    onClick={() => setActiveDropdown(activeDropdown === 'assignee' ? null : 'assignee')}
                    className="flex items-center gap-2 hover:opacity-85 active:scale-95 duration-100 transition-transform text-xs text-zinc-300"
                  >
                    <Avatar initials={assignee.initials} color={assignee.color} size="xs" />
                    <span>{assignee.name}</span>
                  </button>
                  {activeDropdown === 'assignee' && (
                    <div className="absolute top-full left-0 mt-1.5 w-52 bg-zinc-900 border border-zinc-800 rounded-xl shadow-xl z-50 py-1 max-h-48 overflow-y-auto">
                      {TEAM_MEMBERS.map(m => (
                        <button
                          key={m.name}
                          type="button"
                          onClick={() => { setAssignee(m); setActiveDropdown(null); }}
                          className="w-full px-3 py-2 text-xs text-left hover:bg-zinc-800 text-zinc-300 transition-colors flex items-center gap-2"
                        >
                          <Avatar initials={m.initials} color={m.color} size="xs" />
                          <span>{m.name}</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* Project */}
                <div className="relative">
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Project
                  </span>
                  <button
                    type="button"
                    onClick={() => setActiveDropdown(activeDropdown === 'project' ? null : 'project')}
                    className="flex items-center gap-1.5 hover:opacity-85 active:scale-95 duration-100 transition-transform text-xs text-zinc-300"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-violet-500 shrink-0" />
                    <span>{project}</span>
                  </button>
                  {activeDropdown === 'project' && (
                    <div className="absolute top-full left-0 mt-1.5 w-44 bg-zinc-900 border border-zinc-800 rounded-xl shadow-xl z-50 py-1">
                      {PROJECTS.map(p => (
                        <button
                          key={p}
                          type="button"
                          onClick={() => { setProject(p); setActiveDropdown(null); }}
                          className="w-full px-3 py-2 text-xs text-left hover:bg-zinc-800 text-zinc-300 transition-colors"
                        >
                          {p}
                        </button>
                      ))}
                    </div>
                  )}
                </div>

                {/* Due Date */}
                <div>
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Due Date
                  </span>
                  <div className="flex items-center gap-2 text-xs text-zinc-300">
                    <Calendar className="w-3.5 h-3.5 text-zinc-500" />
                    <input
                      type="date"
                      value={dueDate}
                      onChange={e => setDueDate(e.target.value)}
                      className="bg-transparent border-none outline-none focus:ring-0 text-xs text-zinc-300 p-0 m-0 w-28 cursor-pointer select-none"
                    />
                  </div>
                </div>

                {/* Sprint */}
                <div>
                  <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold mb-1.5">
                    Sprint
                  </span>
                  <input
                    type="text"
                    value={sprint}
                    onChange={e => setSprint(e.target.value)}
                    className="bg-transparent border-none outline-none focus:ring-0 text-xs text-zinc-300 p-0 m-0 w-full"
                  />
                </div>
              </div>

              {/* Description Section */}
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] text-zinc-500 uppercase tracking-widest font-semibold">
                    Description
                  </span>
                  <button
                    type="button"
                    onClick={handleAiWrite}
                    disabled={aiWriting}
                    className="inline-flex items-center gap-1.5 text-xs text-cyan-400 hover:text-cyan-300 font-medium cursor-pointer disabled:opacity-50 select-none"
                  >
                    <Sparkles className={`w-3.5 h-3.5 ${aiWriting ? 'animate-spin-slow' : ''}`} />
                    <span>AI Write ✦</span>
                  </button>
                </div>
                <textarea
                  value={description}
                  onChange={e => setDescription(e.target.value)}
                  placeholder="Add a detailed description for this task..."
                  rows={4}
                  className="w-full bg-zinc-900 border border-zinc-800/80 rounded-xl text-sm text-zinc-200 p-3 outline-none resize-none focus:border-violet-500/40 focus:ring-1 focus:ring-violet-500/10 placeholder:text-zinc-600 font-sans"
                />
              </div>

              {/* AI Insights Section */}
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 text-cyan-400 select-none">
                    <Sparkles className="w-4 h-4 shrink-0" />
                    <span className="text-xs font-semibold uppercase tracking-wider">
                      AI Analysis
                    </span>
                  </div>
                  <button
                    type="button"
                    onClick={handleAiAnalysis}
                    disabled={aiAnalyzing}
                    className="bg-cyan-500/10 hover:bg-cyan-500/20 text-cyan-400 border border-cyan-500/20 text-xs px-3 py-1.5 rounded-lg transition-colors cursor-pointer select-none disabled:opacity-50"
                  >
                    {aiAnalyzing ? 'Analyzing...' : 'Generate Analysis'}
                  </button>
                </div>

                {/* AI Output Box */}
                {(aiAnalysis || aiAnalyzing) && (
                  <div className="bg-cyan-500/5 border border-cyan-500/15 rounded-xl p-4 shadow-cyan-glow">
                    {aiAnalyzing && !aiAnalysis ? (
                      <div className="flex items-center gap-2 text-xs text-cyan-400/80 font-mono">
                        <Sparkles className="w-3.5 h-3.5 animate-spin-slow" />
                        <span>Claude is inspecting task metrics...</span>
                      </div>
                    ) : (
                      <div className="prose prose-invert prose-xs text-xs text-zinc-300 space-y-2 leading-relaxed">
                        {aiAnalysis.split('\n').map((line, idx) => {
                          if (line.startsWith('1)') || line.startsWith('2)') || line.startsWith('3)')) {
                            return <h5 key={idx} className="text-cyan-400 font-semibold tracking-wide uppercase mt-3 mb-1 text-[10px]">{line}</h5>;
                          }
                          return <p key={idx} className="m-0 leading-relaxed">{line}</p>;
                        })}
                      </div>
                    )}
                  </div>
                )}
              </div>

              {/* Activity Log */}
              <div className="border-t border-zinc-800 pt-5 space-y-4">
                <span className="block text-[10px] text-zinc-500 uppercase tracking-widest font-semibold">
                  Activity
                </span>
                
                {/* 3 Mock activity items */}
                <div className="space-y-3">
                  <div className="flex gap-3 text-xs">
                    <Avatar initials="SC" color="bg-violet-500" size="xs" />
                    <div>
                      <span className="font-semibold text-zinc-300">Sarah Chen</span>
                      <span className="text-zinc-500"> created this task </span>
                      <span className="text-zinc-600 font-mono text-[10px]">10 days ago</span>
                    </div>
                  </div>
                  <div className="flex gap-3 text-xs">
                    <Avatar initials="AJ" color="bg-zinc-700" size="xs" />
                    <div>
                      <span className="font-semibold text-zinc-300">Alex Johnson</span>
                      <span className="text-zinc-500"> updated priority to </span>
                      <span className="text-amber-500 font-semibold">Urgent</span>
                      <span className="text-zinc-600 font-mono text-[10px]"> 2 days ago</span>
                    </div>
                  </div>
                  <div className="flex gap-3 text-xs">
                    <Avatar initials="DK" color="bg-rose-500" size="xs" />
                    <div>
                      <span className="font-semibold text-zinc-300">David Kim</span>
                      <span className="text-zinc-500"> commented: </span>
                      <span className="text-zinc-400 italic">"Caching logic is staging validated."</span>
                      <span className="text-zinc-600 font-mono text-[10px]"> 1 hour ago</span>
                    </div>
                  </div>
                </div>

                {/* Mock Comment Input */}
                <div className="flex gap-2 items-center bg-zinc-900 border border-zinc-800/80 rounded-xl px-3 py-2">
                  <input
                    type="text"
                    placeholder="Add a comment..."
                    className="flex-1 bg-transparent border-none outline-none text-xs text-zinc-200 focus:ring-0 placeholder:text-zinc-600"
                  />
                  <button
                    type="button"
                    aria-label="Send comment"
                    className="w-6 h-6 rounded-lg hover:bg-zinc-800 flex items-center justify-center text-zinc-500 hover:text-zinc-300 transition-colors cursor-pointer shrink-0 active:scale-95"
                  >
                    <Send className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>

            </div>

            {/* Footer */}
            <div className="px-6 py-4 border-t border-zinc-800 flex gap-3 shrink-0 bg-zinc-950 select-none">
              <button
                type="button"
                onClick={handleSave}
                className="flex-1 h-9 bg-violet-600 hover:bg-violet-500 text-white text-xs font-semibold rounded-lg shadow-sm transition-colors cursor-pointer"
              >
                Save changes
              </button>
              <button
                type="button"
                onClick={handleDelete}
                aria-label="Delete task"
                className="w-9 h-9 border border-zinc-800 hover:bg-red-500/10 text-zinc-500 hover:text-red-400 flex items-center justify-center rounded-lg transition-colors cursor-pointer shrink-0"
              >
                <Trash2 className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
